#!/usr/bin/python3
#
# This file holds all global constants used by the OEC Sychroniser extension
# for the Open Exoplanet Catalogue (OEC) project. Including the mapping from
# XML tag to csv file column name, this must be kept up to date and edited
# manually.


# CONFIG keys:
TOLERANCE = 'tolerance'
CLONED_REPO_NAME = 'cloned_repo'
HOUR = 'hour'
MINUTE = 'minute'
AUTO_STATE = 'auto_on/off'
MAX_PULLS = 'max_pulls'
DEFAULT_CONFIG = {TOLERANCE: 0, CLONED_REPO_NAME: None, HOUR: 0, MINUTE: 0,
                  AUTO_STATE: False, MAX_PULLS: 100}

# Github commit/pull messages:
PULL_MSG = "OEC Synchronizer automatically generated update for: "
UPDATE_MSG_START = ("OEC Synchronizer automatically generated update of ")
NEW_MSG_START = ("OEC Synchronizer automatically generated new XML system " +
                 "file for ")
MSG_MID = " from "
MSG_END = "."
VALIDATION_REQUIRED = "OEC SYNC VALIDATION REQUIRED: "
VALIDATION_START = "OEC Synchronizer thought that "
VALIDATION_MID1 = " looked like "
VALIDATION_MID2 = " in "
VALIDATION_END = (", if pull request is closed without merging, a new file " +
                  "will be generated for this planet on next run. ")

# URL's to exoplanet data:
# URL to csv file containing exoplanets in the Nasa Exoplanet Archive.
NASA_URL = ("http://exoplanetarchive.ipac.caltech.edu/cgi-bin/nstedAPI/"
            "nph-nstedAPI?table=exoplanets&select=*")
# URL to csv file containing all data in the Exoplanet.eu database.
EXOPLANET_URL = "http://exoplanet.eu/catalog/csv"


# Directory names for use in functions:
SYSTEM_DIR = "systems"
# File names for use in functions:
LOG_FILE = "oec_log"
CONFIG_FILE = "config.pkl"
REPO_FILE = "git_repo.pkl"
UPDATE_TRACKER_FILE = "update_tracking.pkl"
NASA_CON_NAME = "nasa_confirmed_exoplanets"
EXO_EU_NAME = "exoplanet_eu_exoplanets"
OAUTH_FILE = "oauth.json"

# File Endings:
XML_END = ".xml"
CSV_END = ".csv"


# Strings used for System xml documents:
# List values:
CONFIRMED_LIST = "Confirmed exoplanets"
# Standard OEC date formate
OEC_DATE = '%y/%m/%d'


# Run command for crontab:
DEMO_RUN_CMD = 'oec_demo.py run'
RUN_CMD = 'oec_sync.py run'

# Help text:
MAIN_DESCRIPTION = ('This program generates automatic updates of system XML ' +
                    'documents for the Open Exoplanet Catalogue (OEC). ' +
                    'Currently it only supports monitoring updates from: ' +
                    NASA_URL + ' and ' + EXOPLANET_URL + '.')

TOLERANCE_HELP = ('Sets the tolerance level for numeric values. The level ' +
                  'should be entered as a percentage value less percentage ' +
                  'sign (decimal percentages are allowed). Any ' +
                  'differences in value below the tolerance level will not ' +
                  'be updated. Tolerance level defaults to 0 (all ' +
                  'defferences are updated).')

INIT_HELP = ('Initialize oec_sync.py program. Must be initialized before ' +
             'first run.')

RUN_HELP = ('Manually preforms a single run of the update ' +
            'program. Does not effect automatic running (if set). Must run ' +
            'oec_sync.py init before run can be called.')

SET_AUTO_HELP = ('Configures automatic running of oec_sync.py ' +
                 'program. Must be configured before automatic updating can ' +
                 'be turned on. Must run oec_sync.py init before set-auto ' +
                 'can be called.')

DESTROY_HELP = ('Removes all program settings, turns off automatic ' +
                'updating and removes existing settings, deletes all ' +
                'unmerged or unclosed pull requests generated by program, ' +
                'deletes all existing branches created by the program. If ' +
                'used, oec_sync.py will be put into an unitinitalized state ' +
                'and init must be run before further use.')

ON_HELP = 'Turns automatic updating on.'

OFF_HELP = 'Turns automatic updating off.'

DOWNSTREAM_HELP = ('MANDATORY: Downstream GitHub owner (user name) / ' +
                   'repository that will be used to create new branches for ' +
                   'each pull request issued to the upstream GitHub ' +
                   'repository (if no upstream repository is given then ' +
                   'downstream will be used to both create branches and ' +
                   'issue pull requests). Must have user name / email and ' +
                   'password for this GitHub repository. This repository ' +
                   'must be the same repository or a fork of the upstream ' +
                   'repository (if upstream repository is given). Either ' +
                   'this repository or the upstream repository must be the ' +
                   'OEC GitHub repository https://github.com/' +
                   'openexoplanetcatalogue/open_exoplanet_catalogue/ or a ' +
                   'fork of it.')

EMAIL_HELP = 'MANDATORY: Email account associated downstream GitHub account.'

UPSTREAM_HELP = ('Upstream GitHub owner (user name) / ' +
                 'repository to which pull requests will be issued from ' +
                 'the downstream GitHub repository. This repository must be ' +
                 'the OEC GitHub repository https://github.com/' +
                 'openexoplanetcatalogue/open_exoplanet_catalogue/ or a ' +
                 'fork of it.')

HOUR_HELP = ('Sets the hour that you would like the updater to run. ' +
             'Must be an integer value between 0-23.')

MINUTE_HELP = ('Sets the minutes after the hour that you would like the ' +
               'updater to run. Must be an integer value between 0-59.')

MAX_PULLS_HELP = ('Sets the maximum number of pull requests / branches that ' +
                  'the program will allow open at any time. Must be an ' +
                  'integer value between 0-250. If set to a lower value ' +
                  'then the current number of pull requests, no existing ' +
                  'pull requests will be removed and no new pull requests ' +
                  'will be generated until the number of open pull requests ' +
                  'is below the current max-pull limit. Max-pull limit ' +
                  'defaults to 100.')